[package]
authors.workspace      = true
edition.workspace      = true
license.workspace      = true
name                   = "claurst-buddy"
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[dependencies]
anyhow       = { workspace = true }
chrono       = { workspace = true }
claurst-core = { workspace = true }
hex          = { workspace = true }
serde        = { workspace = true }
serde_json   = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
