[package]
authors.workspace      = true
edition.workspace      = true
license.workspace      = true
name                   = "claurst-query"
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[dependencies]
anyhow          = { workspace = true }
async-trait     = { workspace = true }
chrono          = { workspace = true }
claurst-api     = { workspace = true }
claurst-core    = { workspace = true }
claurst-plugins = { workspace = true }
claurst-tools   = { workspace = true }
dashmap         = { workspace = true }
dirs            = { workspace = true }
futures         = { workspace = true }
once_cell       = { workspace = true }
parking_lot     = { workspace = true }
serde           = { workspace = true }
serde_json      = { workspace = true }
thiserror       = { workspace = true }
tokio           = { workspace = true }
tokio-stream    = { workspace = true }
tokio-util      = { workspace = true }
tracing         = { workspace = true }
uuid            = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
