[package]
authors.workspace      = true
edition.workspace      = true
license.workspace      = true
name                   = "claurst"
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[[bin]]
name = "claurst"
path = "src/main.rs"

[dependencies]
anyhow             = { workspace = true }
async-trait        = { workspace = true }
base64             = { workspace = true }
chrono             = { workspace = true }
clap               = { workspace = true }
claurst-acp        = { workspace = true }
claurst-api        = { workspace = true }
claurst-bridge     = { workspace = true }
claurst-commands   = { workspace = true }
claurst-core       = { workspace = true, features = ["voice"] }
claurst-mcp        = { workspace = true }
claurst-plugins    = { workspace = true }
claurst-query      = { workspace = true }
claurst-tools      = { workspace = true }
claurst-tui        = { workspace = true }
crossterm          = { workspace = true }
dirs               = { workspace = true }
nix                = { workspace = true }
open               = { workspace = true }
parking_lot        = { workspace = true }
reqwest            = { workspace = true }
serde              = { workspace = true }
serde_json         = { workspace = true }
sha2               = { workspace = true }
tokio              = { workspace = true }
tokio-util         = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
url                = { workspace = true }
urlencoding        = { workspace = true }
uuid               = { workspace = true }

[build-dependencies]
chrono = { workspace = true }
